controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

pythagore_display:
    path: /pythagore/viewDisplayPythagoreAction
    controller: App\Controller\PythagoreController::viewDisplayPythagoreAction

